PROG     = power
SOURCES = build.c compute.c main.c
HDRS = power.h

CFLAGS = -DTORONTO
LDFLAGS  = -lm

FP_TOLERANCE = 0.00001
OUTPUT = power.reference_output
STDIN_FILENAME = /dev/stdin

PATH_TO_SRC = ../../

include $(PATH_TO_SRC)Makefile.common

