SOURCES = pa1.c shell_array.c shell_list.c
HDRS = shell_array.h shell_list.h
PROG = pa1

RUN_OPTIONS = -a 1M.b output1a
OUTPUT = output1a

PATH_TO_SRC=../../

include $(PATH_TO_SOURCE)Makefile.common
