SOURCES = Fheap.c ft.c item.c Fsanity.c graph.c
HDRS = Fheap.h Fsanity.h Fstruct.h graph.h item.h
PROG = ft

RUN_OPTIONS = 1500 100000
OUTPUT = OUT

CFLAGS = 
LDFLAGS = 

PATH_TO_SRC = ../../

include $(PATH_TO_SRC)Makefile.common
