SOURCES = pa4.c manip.c hbt.c build.c
HDRS = pa4.h manip.h hbt.h build.h
PROG = pa4

RUN_OPTIONS = -q ops0.b treeOutput0
OUTPUT = treeOutput0

PATH_TO_SRC=../../

include $(PATH_TO_SOURCE)Makefile.common
