PROG = parson
SOURCES = tests.c parson.c
HDRS = parson.h

CFLAGS = -O0 -g -Wall -Wextra -std=c99 -pedantic-errors
LDFLAGS =

OUTPUT = OUT
STDIN_FILENAME = /dev/stdin

PATH_TO_SRC = ../

include $(PATH_TO_SRC)Makefile.common

