PROG = anagram
SOURCES = anagram.c
HDRS =

RUN_OPTIONS = words 2
STDIN_FILENAME = input.OUT
OUTPUT = anagram.reference_output

CFLAGS =
LDFLAGS =

PATH_TO_SRC=../../

include $(PATH_TO_SRC)Makefile.common

