SOURCES = assign.c hcg.c maze.c vcg.c channel.c main.c option.c
HDRS = assign.h hcg.h option.h vcg.h channel.h maze.h types.h
PROG = yacr2

RUN_OPTIONS = ./input2.in
OUTPUT = OUT

CFLAGS = -I.. -DTODD
LDFLAGS=

PATH_TO_SRC=../../

include $(PATH_TO_SRC)Makefile.common

