# placeholder for more tools options
# for now just load defaults

include Makefile.external

FMT ?= EXTERNAL_FMT
CC ?= EXTERNAL_CC
C3 ?= EXTERNAL_C3
THREEC ?= EXTERNAL_THREEC
THREEC_WORKTREE ?= EXTERNAL_THREEC_WORKTREE


