# placeholder for more tools options
# for now just load defaults

# requires
# PATH_TO_SRC


include $(PATH_TO_SRC)../tools/Makefile.external

FMT ?= $(EXTERNAL_FMT)
CC ?= $(EXTERNAL_CC)
C3 ?= $(EXTERNAL_C3)
THREEC ?= $(EXTERNAL_THREEC)
THREEC_WORKTREE ?= $(EXTERNAL_THREEC_WORKTREE)


