EXTERNAL_FMT = /home/kyle/Documents/Projects/3C/checkedc-clang/llvm/cmake-build-release/bin/clang-format
EXTERNAL_CCClang = /home/kyle/Documents/Projects/3C/checkedc-clang/llvm/cmake-build-release/bin/clang
EXTERNAL_C3 = /home/kyle/Documents/Projects/3C/C3/_build/default/src/main.exe
EXTERNAL_THREEC = /home/kyle/Documents/Projects/3C/checkedc-clang/llvm/cmake-build-release/bin/3c
EXTERNAL_THREEC_WORKTREE = /home/kyle/Documents/Projects/3C/checkedc-clang

